### ISSUE TITLE
Buggy top and bottom slider

### ISSUE THREAD

**Issue by Gargo** [gelemias/RDGliderViewController#8]
just try to show them in fullscreen if you can)

**Comment by gelemias** [comment]
Hi @Gargo, can you be more specific? please describe the steps, device or scenario to reproduce the error,
Thank you.

**Comment by Gargo** [comment]
What don't you understand? You tap a button to view a "popup" and try to move it to make it fully appear with pan gesture
device - simulator 5s, 10.2 (but it seems it will appear on real device too)

**Comment by gelemias** [comment]
In order to get the GliderViewController filling the entire view you need to specify an offset of 1 (100% of container's length) 

e.g:
`[[RDGliderViewController alloc] initOn:self WithContent:[ContentViewController new] type:RDScrollViewOrientationBottomToTop AndOffsets:@[@0, @0.5, @1]];
`
these offsets will set 2 steps when dragging towards the top of the view:
-  @0 = not visible (underneath of the view)
- @0.5 = middle of container's lenght (height for RDScrollViewOrientationBottomToTop)
- @1 = fullscreen (content.x = container.x)

@Gargo is this what you mean?

**Comment by Gargo** [comment]
@gelemias man, do you troll me? fullscreen means view's frame conforms conditions:
1)origin == CGPointZero
2)size == screenSize

**Comment by gelemias** [comment]
@Gargo the control handles the origin and size of the Content, honestly I don't know what you are doing to reproduce that error. That constructor I wrote you above is what you need to do to show it in fullscreen
